In [6]:
import tensorflow as tf

In [65]:
def Print(t):
    sess = tf.Session()
    with sess.as_default():
        print(t.eval())

def multiply_col_by_col(t1, t2):
    # Expected nxm
    shape1 = t1.shape
    shape2 = t2.shape
    
    t1col = tf.reshape(t1, (shape1[0], shape1[1], 1))
    t2row = tf.reshape(t2, (shape2[0], 1, shape2[1]))
    tmul = tf.matmul(t1col, t2row)
    ones = tf.ones_like(tmul)
    mask = tf.matrix_band_part(ones, 0, -1)
    upper_triangular_flat = tf.boolean_mask(tmul, mask)

    removed_len = tf.Dimension( int(shape1[1]) * (int(shape1[1]) - 1) / 2 )
    
    #res = tf.reshape(upper_triangular_flat, (shape1[0], 24))
    
    return(tf.reshape(upper_triangular_flat, (shape1[0], shape1[1]*shape2[1] - removed_len)))

In [83]:
t1 = tf.constant([[1,2,3],[4,5,6]])
t2 = multiply_col_by_col(t1, t1)
t3 = multiply_col_by_col(t1, t2)

x_ = tf.expand_dims(t1, 0)
y_ = tf.expand_dims(t1, 1)
z = tf.reshape(tf.add(x_, y_), [-1, 2])
Print(x_)

#Print(t1)
Print(t2)
#Print(t3)

[[[1 2 3]]

 [[4 5 6]]]
[[ 1  2  3  4  6  9]
 [16 20 24 25 30 36]]


In [66]:
shape1 = t1.shape
shape2 = t2.shape

t1col = tf.reshape(t1, (shape1[0], shape1[1], 1))
t2row = tf.reshape(t2, (shape2[0], 1, shape2[1]))
tmul = tf.matmul(t1col, t2row)

ones = tf.ones_like(tmul)
mask = tf.matrix_band_part(ones, 0, -1)
upper_triangular_flat = tf.boolean_mask(tmul, mask)

print(shape1[1],shape2[1])

removed_len = tf.Dimension( int(shape1[1]) * (int(shape1[1]) - 1) / 2 )

res = tf.reshape(upper_triangular_flat, (shape1[0], shape1[1]*shape2[1] - removed_len))
Print(res)

3 6
[[ 1  2  3  4  6  9  4  6  8 12 18  9 12 18 27]
 [27 36 36 48 48 48 48 48 64 64 64 48 64 64 64]]


In [60]:
t1 = tf.constant([[1,2,3],[3,4,4]])
t2 = multiply_col_by_col(t1, t1)


ValueError: Cannot reshape a tensor with 18 elements to shape [2,6] (12 elements) for 'Reshape_205' (op: 'Reshape') with input shapes: [2,3,3], [2] and with input tensors computed as partial shapes: input[1] = [2,6].